### PR TITLE
added example for "catch-all" routes

### PR DESCRIPTION
**Pull request by notoriousno**
#110 wanted to see an example of a catch-all in the docs.  The docs are a bit sparse and more examples should be added.

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
:+1: :100: 

Thanks!

**Comment by glyph** [comment]
Thanks. This is indeed a hole in the docs.  It seems weird to blanket handle what should be 404s with a redirect though… is this a common practice?

**Comment by notoriousno** [comment]
Thanks for the merge @glyph I'm glad this project isn't dead. I thought for sure all merge requests were falling on deaf ears :D. You've reminded me that I was supposed to make a new merge request which had a better way of catching all 404 errors using Werkzeug's exceptions.

**Comment by BenjamenMeyer** [comment]
This is not about 404s but about how to route. See the Mimic Swift changes I put forward for the difference.

**Pull request merged**
