### PR TITLE
[requires.io] dependency update on master branch

### PR DESCRIPTION
**Pull request by mithrandi**

### CODE REVIEW

**Review by wsanchez — APPROVED** [review]

**Comment by wsanchez** [comment]
@adiroiban Yeah here's codecov upload failing again FYI…

**Comment by adiroiban** [comment]
@wsanchez does klein need coverage reported for every python version?

I guess that codecov is under  some stress now, with the security issue they have.

One option is to use the python codecov uploader in a script and auto-retry on error(after a delay)

codecov upload failures do come from time to time.

But for twisted, I am planning to push all coverage reports as artifact, download them in a job at the end do a single upload (with retry) ... it's extra work on our side but might help with the coverage reporting...
At the same time, if we have all the coverage files in a single job, we can implement our own coverage percentage diff and reinvent codecov

but for now, I am waiting 2 more weeks for codecov.io security incident to pass and see what changes will be done by codecov.io

**Comment by wsanchez** [comment]
@adiroiban It really should be sufficient to upload from one build only. Pretty sure that'll catch everything… if coverage drops we'll know, and can add another from the matrix.

**Comment by wsanchez** [comment]
The hardest part of doing our own Codecov equivalent MVP would be to diff against master. 

If we could do that and upload an HTML thing showing the diff we are all set.

We could also upload the result to Codecov while ignoring errors to get Codecov's other features when it is working.

**Comment by adiroiban** [comment]
I am using  diff_cover for some time to get a local diff report - https://github.com/Bachmann1234/diff_cover  

Just like codecov, it uses the cobertura xm format.
I don't think it has HTML report... for me a text output is enough.

But the diff doesn't support branch coverage reporting.
This is something that codecov.io supports.

---------

I now saw this and I can give it a try  https://pypi.org/project/pycobertura/

My issues is... where you store the HTML ?

Artifacts are not nice as they are archives and you can't just see them directly as HTML + CSS 

Twisted ORG has Azure credits...so maybe we can store them as Azure Blob ...and with Blob Lifecycle Management we can have them auto-removed in 30 or 90 days.

**Pull request merged**
