### PR TITLE
delet this

### PR DESCRIPTION
**Pull request by not-glyph**
I'm testing #323 .

### CODE REVIEW

**Comment by glyph** [comment]
no its good

**Comment by not-glyph** [comment]
no

**Comment by glyph** [comment]
bye

**Comment by glyph** [comment]
So it appears the conclusion of this experiment is that external contributors can only request re-review *from the contributor who did their original review*.  Project members can dismiss that (orphaning the pull request; bad) or manually toss it back to the team.

cc @markrwilliams

**Pull request closed without merging**
