### PR TITLE
Add incremental for versioning

### PR DESCRIPTION
**Pull request by hawkowl**
This PR adds incremental, which is nicer versioning.

### CODE REVIEW

**Comment by glyph** [comment]
I want to just click the green button here, but years of setuptools FUD have made me fearful and distrustful of `setup_requires`.  @dstufft, am I now a fool for holding on to this fear, or merely recalling hard-won wisdom?

**Comment by dstufft** [comment]
Well, having a ``setup_requires`` is inherently more fragile with more broken edge cases than not having a ``setup_requires`` (much in the way that having an ``install_requires`` is inherently more fragile with more broken edge cases than not having an ``install_requires``). The top issues are (from memory):

* ``setup_requires`` suffers from the terrible problem of needing to delay imports some how (e.g. no ``import incremental`` at top level).
* ``setup_requires`` is downloaded and installed by setuptools not pip, so there's often confusion that comes in the edges where setuptools and pip have different behavior. An example is ``pip install -i https://example.com/index/ klein`` would still try to pull incremental from PyPI unless you added extra config files to point setuptools away from PyPI and towards your custom repo.
* ``setup_requires`` will be invoked for *all* invocations of ``setup.py``, even ones that don't need it like ``setup.py clean`` unless you go out of your way (like pyca/cryptography did) to fix that.

That being said, a lot of the problems with having a ``setup_requires`` become way less important, particularly for pure Python packages, since we now have Wheels and ``setup_requires`` simply does not apply and in all likelihood most people installing a pure Python project with a wheel in 2016 are going to be installing the wheel not the sdist. This makes the above edge cases far less of a big deal and tips the scale in the favor of using the mechanisms for abstraction in ``setup.py``, flawed as the mechanism may be, since they'll be used by an increasingly smaller subset of people.

That being said, similarly to ``install_requires``, it's largely a person choice of how much benefit you're gaining from whatever is in the ``setup_requires`` and whether the "cost" of the ``setup_requires`` outweighs the benefits or not. My own metric tends to be that for your average project, once you start getting above trivial code (like a ``with open(): read()``) the math pretty quickly favors using ``setup_requires``, especially for pure Python programs, unless you have some evidence or reason to believe that installation via sdist is a significant part of your user base.

**Comment by glyph** [comment]
@dstufft thanks for the expansive reply.

Let me summarize to see if I understand: as long as we generate wheels for all relevant platforms, then the `setup_requires` nonsense only gets invoked on the wheel-building computer, not on the installation target, and we can probably control the wheel-building system enough that it will work?

**Comment by dstufft** [comment]
@glyph Yea, with the whole not 100% things support wheels so you'll still get some cases where end users install sdist, but they'll generally work fine in the common case, and there are work arounds for all issues in the edge cases they don't work (and overall, less impact thanks to most using wheels).

**Comment by glyph** [comment]
@hawkowl do we have an officially-documented process for Klein's releases that includes building wheels?  If so, I'm inclined to click 'merge' on this…

**Comment by hawkowl** [comment]
@glyph no, but I can make one :) . I publish wheels on all the projects I can anyway.

**Comment by hawkowl** [comment]
See https://github.com/twisted/klein/pull/109

**Comment by glyph** [comment]
Now that an actual formally documented process requires that we do the right thing re: @dstufft , I'm going to land this.

**Comment by glyph** [comment]
hey @dstufft - FYI, this breaks `pip install -e` for me, but not for hawkowl.  `pip install -e` installs all the deps except for incremental, and, for some weird reason, six.  `pip install` works fine.

I'm sort of inclined to roll this back out as a result.  I use `-e` environments pretty much everywhere.

**Comment by glyph** [comment]
Figured it out!!!  No back-out required.

The problem is that older versions of Klein generated a `.egg-info` file in `Klein/klein.egg-info`.  The relevant change that "broke" it was actually the move to `src/` because it now generates the egg-info file in `Klein/src/klein.egg-info`, but `setup.py develop` was picking the old one up for some reason.  My repository-cleaning script wasn't fixing this because of course it skips `.egg-info` files since you need them around to make stuff importable in many circumstances.

When I deleted the old `.egg-info` everything went back to working.

**Pull request merged**
