### PR TITLE
stop the interaction of hypothesis and disttrial from hanging the tests

### PR DESCRIPTION
**Pull request by glyph**
something that disttrial is doing is making it so that a threading.local() reference being kept by a recursive hypothesis strategy (but only if it is actually recursive!) retained at module scope getting torn down during interpreter finalization prevents both workertrial and the parent disttrial processes from exiting, hanging forever

### CODE REVIEW

**Comment by glyph** [comment]
see also https://github.com/python/cpython/pull/28525

**Review by adiroiban — APPROVED** [review]
Hi.
I have close to zero experience with hypothesis.

But I guess the changes are fine and this can be merged.

Thanks!

**Comment by exarkun** [comment]
Another reference - https://github.com/HypothesisWorks/hypothesis/issues/3585

**Comment by glyph** [comment]
@exarkun does that reference tell us when we can remove this gross hack? :)

**Comment by exarkun** [comment]
> @exarkun does that reference tell us when we can remove this gross hack? :)

[This comment](https://github.com/HypothesisWorks/hypothesis/issues/3585#issuecomment-1453521883) seems to suggest the fix will be in the next bugfix release of Python 3.11 and the next major release.  There is also [an upstream bug report](https://github.com/python/cpython/issues/102126) which is closed now (and seems like a duplicate of the cpython bug report linked here, above).

**Comment by glyph** [comment]
> > @exarkun does that reference tell us when we can remove this gross hack? :)
> 
> [This comment](https://github.com/HypothesisWorks/hypothesis/issues/3585#issuecomment-1453521883) seems to suggest the fix will be in the next bugfix release of Python 3.11 and the next major release. There is also [an upstream bug report](https://github.com/python/cpython/issues/102126) which is closed now (and seems like a duplicate of the cpython bug report linked here, above).

Thanks for those references!

**Pull request merged**
