### PR TITLE
Documentation enhancements

### PR DESCRIPTION
**Pull request by brighid**
There's still quite a bit I want to do, but I feel like these are upgrades that are still tractable to review. This series of patches, as well, is still easy to change in response to reviews.

### CODE REVIEW

**Comment by glyph** [comment]
Thanks for submitting these doc enhancements.  Sorry it took so very long to have a look at this.  I've added a recurring task to periodically look at all my Github projects so hopefully I'll get back to it soon.

If you could address the merge conflicts I could probably land it sooner - this mostly looks like good stuff, but it's a lot of changes at once.  If you could apply a few of them in separate PRs I will do my best to look at them in less than 8 months :).

**Comment by brighid** [comment]
I imagine some of this has also gone stale in the intervening months. I'll rebase, take care of the conflicts, and see about splitting this into 2-3 PRs.

**Comment by glyph** [comment]
Thanks, and sorry again for the long delays.

**Comment by glyph** [comment]
@brighid - As you can see the frequency of my checking in with PRs is going down :).  You mentioned splitting this into 2-3 PRs; should we just close this one in the meanwhile?

**Comment by brighid** [comment]
Yeah, I'll just open new PRs — sorry I haven't been able to follow up on this.

-B

**Comment by glyph** [comment]
No worries.  I have enough trouble keeping up with my own projects to criticize anyone for not contributing to someone else's :).

**Pull request closed without merging**
