### PR TITLE
RFC: Drop CI support for Python 3.5

### PR DESCRIPTION
**Pull request by wsanchez**
Usage stats via `pypistats python_minor klein --last-month`:

| category | percent | downloads |
|----------|--------:|----------:|
| 2.7      |  46.53% |    10,612 |
| 3.7      |  21.11% |     4,815 |
| 3.6      |  21.09% |     4,809 |
| 3.8      |   7.10% |     1,619 |
| 3.5      |   2.30% |       525 |
| null     |   1.64% |       374 |
| 3.4      |   0.23% |        52 |
| 2.6      |   0.00% |         1 |
| Total    |         |    22,807 |

Date range: 2020-05-01 - 2020-05-31

### CODE REVIEW

**Comment by twm** [comment]
I'm still using Klein on Python 3.5. :( What's the motivation here, saving builder time?

**Comment by wsanchez** [comment]
@twm That's the only thing right now. We need to add 3.8 to the matrix.

Also, I think we plan to drop 2.7 in January, and I'd like to actually start using Py3 for real in the code, especially inline type hints, and IIRC 3.5 is going to be a PITA on that front.

So I want to start the discussion.

**Comment by glyph** [comment]
I'm inclined to say @twm's usage is enough of a reason to keep it around, but please do let us know when you're ready for it to drop :)

**Comment by glyph** [comment]
@twm FYI: https://www.python.org/dev/peps/pep-0478/#release-schedule implies that 3.5 EOL has already passed, so you might want to move on!  It doesn't have anything as definitive as https://www.python.org/dev/peps/pep-0494/#and-beyond-schedule 's end date, but it does say "no specific plans".

**Comment by twm** [comment]
I'm using Python 3.5 from Ubuntu 16.04 in a few projects (it is maintained _enough_, whatever upstream's plans), but most should be straightforward to upgrade. I'm already working on that. In the complicated case &mdash; Python ABI compatibility, ugh &mdash; I could make a lateral move to PyPy 3.6.

I'm fine with dropping 3.5 support if it's motivated by features or maintenance burden &mdash; I've wished for inline type annotations myself! I wouldn't want to impede all the progress @wsanchez is making. What would rather avoid is dropping widespread Pythons based on release schedules alone.

**Comment by glyph** [comment]
Fair enough; it’s really the security support schedule which is the issue (and for compliance with things like PCI, you often *have* to care what upstream says) rather than the release schedule that’s the issue. But 3.5 is a real bummer of a release just due to all the goodies in 3.6.  I imagine that we’ll be somewhat slower to drop 3.6, then not really feel much pressure to drop a release until whichever one introduces lazily-evaluated annotations :).

**Comment by wsanchez** [comment]
Looks like this PR somehow has extra diff action in it; needs cleaning up.

**Comment by glyph** [comment]
@twm - what are your upgrade plans looking like these days?

**Comment by twm** [comment]
Things are unchanged on my side. I'm still fine with dropping 3.5. Don't hold up progress on Klein because it might cause me mild inconvenience.

Definitely don't drop 3.6 until we have a Twisted release with the 3.7 chunked multipart fix (https://github.com/twisted/twisted/pull/1207) &mdash; that would block adoption of 3.7.

**Comment by wsanchez** [comment]
I'm not aware of anything added in 3.7 that is compelling for Klein to make such a much based on language features, so I don't see much cause to drop 3.6.

**Comment by arnimarj** [comment]
Just to add one point: one good reason to hold on to Python 3.6 support is that PyPy3 is still at 3.6

**Comment by wsanchez** [comment]
@arnimarj Dropping 3.6 is out of scope for this PR, FWIW.

**Comment by wsanchez** [comment]
CI is going to keep failing here due to changing the target version for black to Python 3.6 from 2.7.

PR #328 changing that same config from 2.7 to 3.5. I don't want to commit the reformatted source code in this PR first, as that may invite conflicts, so I'll sit on merging the other PR first.

**Pull request merged**
