### PR TITLE
Extend and Compose

### PR DESCRIPTION
**Pull request by notoriousno**
Finally had some time over the break to get this out the door! This merge request stems from conversations over at #72. This is an example of how ``Klein`` functionality can be extended without subclassing, as well as how non-global composability can be leveraged.

For reviewers looking to see the final output on your local machine, do the following:

1. checkout the repo ``git clone git@github.com:notoriousno/klein.git``
1. switch to the branch ``git checkout extend-and-compose``
1. ``cd docs``
1. generate Sphinx doc ``make html``
1. serve the static files ``twist web -p 9000 --path _build/html/``
1. go to ``http://localhost:9000/examples/extendandcompose.html``

### CODE REVIEW

**Comment by notoriousno** [comment]
Appended changes in reference to #149. Needs review

**Comment by glyph** [comment]
One reservation I have with this approach here is that I feel like "JSON API with authentication" is something that we should (and will, soon, if I have any time to work on https://github.com/glyph/klein/tree/form-hacks) have a built-in way to deal with; when we acquire said built-in way, it's going to be odd that the documentation shows doing it in a much less featureful, much more manual way as an example.

Is there any more application-specific example that we could use here, something that wouldn't conflict with zillions of other higher-level wrappers and hopefully someday soon Klein itself?

**Comment by notoriousno** [comment]
Sure there are other examples I could use...I simply can't think of one at the moment :) (but that's mostly because I'm thinking about 1000 other things currently). At the time of writing this example, there were no such aspirations for klein.

One thing I'd been thinking about was doing some sort of Swagger/RAML schema output-er, but that will require 3rd party modules and I'd like to limit that if possible. I'm totally up for suggestions.

**Comment by glyph** [comment]
> Sure there are other examples I could use...I simply can't think of one at the moment :)

No rush :-).

**Comment by glyph** [comment]
> One thing I'd been thinking about was doing some sort of Swagger/RAML schema output-er, but that will require 3rd party modules and I'd like to limit that if possible. I'm totally up for suggestions.

For a documentation example, it's better to choose something deliberately unhelpful.  If we have a RAML layer, it should be built in, not hiding in a documentation example.  My suggestion would be something like middleware that uppercases all responses or something :)

**Comment by glyph** [comment]
Since I don't think there's good consensus that this approach makes sense, and there's been no motion for multiple years, I'm going to close this.

I still think there's some room for documentation of compositional idioms with Klein, so this is just closed because I don't think this specific change is going to land, not because the idea was a bad one.

As always, the effort you've put towards improving Klein is much appreciated, and you should always feel free to reopen if you ever have the inclination to put more work towards this :-).

**Pull request closed without merging**
