### PR TITLE
various tox cleanups

### PR DESCRIPTION
**Pull request by wsanchez**
This does a number of things:
 * Displays coverage output for uncovered code when you run a `coverage-*` environment
 * Orders tests so that more recent Python and Twisted versions tend to run first.
 * Adds a `mypy` environment, not yet enabled in the `envlist` (or Travis).

### CODE REVIEW

**Comment by wsanchez** [comment]
OK, ready for review.

**Comment by wsanchez** [comment]
OK this is ready for review

**Comment by wsanchez** [comment]
Gonna make this more bite-sized.  Subtasks:
 * #183: Update pypy

**Comment by dpnova** [comment]
Are you using mypy with klein @wsanchez ? How do you find it if so?

**Comment by wsanchez** [comment]
#187 is the last part of this, so closing this in favor of that.

**Comment by wsanchez** [comment]
@dpnova: Yes, I am, and I think it's got some flaws but is way better than not having it.  The `mypy` tox environment just got merged to master, FYI.

**Comment by dpnova** [comment]
Thanks!

**Pull request closed without merging**
