### PR TITLE
[WIP] Add Tox environment to build the API docs

### PR DESCRIPTION
**Pull request by wsanchez**

### CODE REVIEW

**Comment by wsanchez** [comment]
@mthuurne: I have this using Python 3 to test master with Py3 but I'm not sure how to use the command line to actually generate documentation for `klein`.

Any chance you can help me get that fixed up?  That should help with getting https://github.com/twisted/pydoctor/issues/96 closed out, I think.

**Comment by mthuurne** [comment]
The problem being that pydoctor runs but produces an empty HTML skeleton? Try replacing `--add-module=klein` with `--add-package=${toxinidir}/src/klein`.

With that change, pydoctor will start processing `klein`'s code, but it then crashes with an `AttributeError`. I'll look into that and fix it in pydoctor.

By the way, you can drop the dependency on Epydoc: the parts of Epydoc that pydoctor depends on were merged into pydoctor's source tree.

**Comment by mthuurne** [comment]
I have [a fix for the crash](https://github.com/twisted/pydoctor/pull/173). With this, pydoctor no longer crashes on Klein, but the output still contains some flaws:

- the `klein.resource` module is linked as `klein.resource 0`
- the aliases in `klein.interfaces` are not detected as such and end up in the documentation as variables instead

**Comment by mthuurne** [comment]
The problem with [the aliases](https://github.com/twisted/klein/blob/66b8d751/src/klein/interfaces.py#L26) is that pydoctor sees the assignment inside `if TYPE_CHECKING:` and marks `IRequiredParameter` etc. as variables because a non-trivial expression is assigned.

I'm not sure whether pydoctor is doing anything wrong here: it is obviously not producing the desired result in this case, but when there are conflicting assignments, it has to pick something. Using the first assignment feels just as valid as picking the last assignment.

You could work around this issue by placing the runtime aliases before the type checking definitions. Or even better, check whether the [zope.interface plugin for mypy](https://github.com/Shoobx/mypy-zope/) obsoletes these definitions.

**Comment by mthuurne** [comment]
The problem with `klein.resource` is a different manifestation of the same issue: both branches of an `if TYPE_CHECKING:` statement assign to it and that creates a duplicate entry: one as a variable and one as a module.

Anyway, pydoctor is running, so that should satisfy the goal of this PR. I created [this pydoctor issue](https://github.com/twisted/pydoctor/issues/174) to discuss possible solutions for handling duplicate definitions due to `if TYPE_CHECKING:` trickery.

**Comment by wsanchez** [comment]
@mthuurne Thanks for the help!  I tried updating the CLI but I'm still not getting any of klein's content in here.  I'll look at the `TYPE_CHECKING` issue once we get the content going.

**Comment by mthuurne** [comment]
Ah sorry, I copied that string from a shell script I used for testing. It should be `--add-package={toxinidir}/src/klein` instead, so drop the `$`.

**Comment by wsanchez** [comment]
ARGH! I should have caught that.

**Comment by wsanchez** [comment]
OK awesome.  `klein.resource` is a self-inflicted wound in `klein`.

**Pull request merged**
