### PR TITLE
Implemented TODO app example

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by glyph** [comment]
I want to just hit "merge" here, but there are no tests for this code.  I'm not saying that it's not acceptable, but rather that the review process has to be a lot longer because I need to carefully evaluate whether the example works or not, rather than trusting the tests are covering it. Would it be possible for you to add some unit tests which cover this documentation?  If not, I'll try to review it when I have time (although resources to review Klein issues are quite limited).
  Thanks!

**Comment by brighid** [comment]
I've been trying to clean this up a bit on https://github.com/brighid/klein/tree/todo-list-example-app

**Comment by brighid** [comment]
It's been a year. Probably time to close this. The time investment in cleaning up this branch is non-trivial and the error handling docs that did not exist when the PR was created are better than the proposal here.

**Comment by glyph** [comment]
@brighid - OK. Clearly the original submitter is not going to clean it up at this point :)

**Pull request closed without merging**
