### PR TITLE
Add type hints for klein.test.test_app

### PR DESCRIPTION
**Pull request by wsanchez**
Add type hints for `klein.test.test_app`

### CODE REVIEW

**Comment by wsanchez** [comment]
Currently erroring out in Mypy:

```console
mypy run-test: commands[0] | mypy --cache-dir=/Users/wsanchez/Dropbox/Developer/Twisted/klein/.tox/mypy_cache --pretty release.py setup.py src
src/klein/test/test_app.py:529:10: error: Argument 1 has incompatible type
"Callable[[Any, str], Union[Union[str, bytes, Any, Any], Awaitable[Union[str, bytes, Any, Any]]]]";
expected "Union[KleinRouteFunction, KleinRouteMethod]"  [arg-type]
            @app.route("/user/<name>")
             ^
src/klein/test/test_app.py:533:10: error: Argument 1 has incompatible type
"Callable[[Any, int], Union[Union[str, bytes, Any, Any], Awaitable[Union[str, bytes, Any, Any]]]]";
expected "Union[KleinRouteFunction, KleinRouteMethod]"  [arg-type]
            @app.route("/post/<int:postid>", endpoint="bar")
             ^
Found 2 errors in 1 file (checked 48 source files)
```

I think this is due to the additional arguments to `Klein.route()`… I forget if we had a way to deal with that.

@graingert Did we have an idea for that or am I SOL?

**Comment by wsanchez** [comment]
OK I think I'm remembering that the problem here isn't that we are defining a function with variable arguments, but that we want to define a type that fit for a function with some arguments and maybe some other arbitrary arguments and keyword arguments.

**Comment by wsanchez** [comment]
I might be wishing for https://github.com/python/mypy/issues/5876

**Comment by adiroiban** [comment]
is this ready for review or still a draft ?

**Comment by wsanchez** [comment]
Still a draft… not sure what the best fix for the Mypy error is.

**Comment by glyph** [comment]
#589 might make this a little easier.

**Comment by glyph** [comment]
(Including PEP 0612)

**Comment by glyph** [comment]
The only delta between #592 and this is a single test to address a coverage gap in a test fixture so I'm going to approve here and merge that in to land.

**Review by glyph — APPROVED** [review]

**Pull request merged**
