### PR TITLE
Use twisted/python-info-action

### LINKED ISSUE #458: Use python-info-action
@adiroiban says:

>There is this https://github.com/twisted/python-info-action which tries to share thinks like "Workflow information" ... maybe we can have "Workflow information" inside that action and use the action in klein and other Twisted projects.

Sounds like a plan.

### PR DESCRIPTION
**Pull request by altendky**
Closes #458.

### CODE REVIEW

**Comment by altendky** [comment]
So I notice that the order is different within the JSON objects.  Would we want them sorted?

**Comment by altendky** [comment]
There is also a bit different formatting.  Both the headings and that the new action outputs lines separately resulting in more time stamps vs. the existing `echo` that just outputs newlines.  (or something)

**Comment by wsanchez** [comment]
I'm not sure how this is useful in a standalone job.

For example, it's printing information about the python in `/usr/bin/python`, which is a Python2.7 installed into the system, and not the Python we use in any of the jobs below.

My original reason for adding the `Workflow Information` job was to have a very basic job that simply verified that the GHA machinery was working and to get a  view into the GHA setup before I had ever written any other GHA jobs.  I'm not sure it's all that useful any more; it's mostly there because it's harmless and maybe someday will show that GHA is completely busted and not something else.

So I would propose that we either remove that job, or leave it as it was, and put the `python-info-action` step into each job, below the `Install Tox` step.  I'd also give it a name (`Python Information`).  That way `python-info-action` is providing useful information about the Python environment for (matrix item within) each job.

**Comment by altendky** [comment]
Yeah, I was blindly starting something here with no context beyond the request Adi put over in the action repo.  I'll add it to each job, that's how I have used it as well.

Though it does bug me it doesn't run in the tox env.  `:]`  Hmm, probably wouldn't be hard to get the env Python info if you prebuilt the env which I've started doing.  Though it still wouldn't get the other bits tox does.  Anyways...

As to the existing job, is there a particular upside to leaving it as it was vs. reducing the code by using the action?  Due to the groups the irrelevant Python info isn't 'in the way'.  But sure, just deleting the job is certainly fine by me as well.

Update incoming.

**Comment by wsanchez** [comment]
> Though it does bug me it doesn't run in the tox env. `:]` Hmm, probably wouldn't be hard to get the env Python info if you prebuilt the env which I've started doing. Though it still wouldn't get the other bits tox does. Anyways...

That's a good point, but that suggests that it should be a dependency in Tox, and invoked at the start of the `commands` in each environment… instead of a GHA thing.

What do you mean by "prebuilt the env"? I don't think I'm familiar with that.

> As to the existing job, is there a particular upside to leaving it as it was vs. reducing the code by using the action? Due to the groups the irrelevant Python info isn't 'in the way'. But sure, just deleting the job is certainly fine by me as well.

…I vote for delete.  It's easy to restore if we suddenly miss it.

**Comment by altendky** [comment]
> > Though it does bug me it doesn't run in the tox env. `:]` Hmm, probably wouldn't be hard to get the env Python info if you prebuilt the env which I've started doing. Though it still wouldn't get the other bits tox does. Anyways...
> 
> That's a good point, but that suggests that it should be a dependency in Tox, and invoked at the start of the `commands` in each environment… instead of a GHA thing.

Yup, I had thought about making a package for it and using that package in tox and in the action.  Hadn't bothered yet.

> What do you mean by "prebuilt the env"? I don't think I'm familiar with that.

https://tox.readthedocs.io/en/3.21.4/config.html#cmdoption-tox-notest
```
--notest
    skip invoking test commands.
```
So you can have tox build the env in one command/step and then run in that env in the next.  I don't know if it's obviously better always or anything, but I saw it somewhere...  I think Grainger was doing it?  and figured it'd be nice to separate out a verbose log of dependency installation from the actual test running.  Nice for log viewing and also let's you see the time each bit takes more easily.  I think I actually added it at a point where I was dealing with some catastrophic pip backtracking.

https://github.com/altendky/ssst/blob/ab991de3385ee513b5beefbc19351aa84c16aaf2/.github/workflows/ci.yml#L114-L119
```python
      - name: Setup tox environment
        run: |
          tox -vv --notest -e ${{ matrix.task.tox }}-${{ matrix.python.tox }}-${{ matrix.qt_library.tox }}
      - name: Test
        run: |
          tox -e ${{ matrix.task.tox }}-${{ matrix.python.tox }}-${{ matrix.qt_library.tox }}
```

> > As to the existing job, is there a particular upside to leaving it as it was vs. reducing the code by using the action? Due to the groups the irrelevant Python info isn't 'in the way'. But sure, just deleting the job is certainly fine by me as well.
> 
> …I vote for delete. It's easy to restore if we suddenly miss it.

Update incoming.

**Comment by wsanchez** [comment]
OK I think this is an improvement and we should merge.

We can try the rebuild trick to be better info, but that can be next.

**Review by wsanchez — APPROVED** [review]

**Pull request merged**
