### PR TITLE
Release 15.3.1 which _actually_ has py3 metadata

### PR DESCRIPTION
**Pull request by glyph**
Oops.

### CODE REVIEW

**Comment by hawkowl** [comment]
but... py3.3 (also 3.5, even tho travis is screwy and doesnt let us test that automatically yet)

**Comment by glyph** [comment]
Travis does let us test it automatically.  In fact Treq had a release today that supports it.  Do you want me to add it to the test matrix in this branch?

**Comment by hawkowl** [comment]
Sure -- but we had to do an [ugly hack](https://github.com/crossbario/crossbar/blob/master/.travis.yml#L38) for Crossbar.io.

**Comment by glyph** [comment]
Actually declaring what version of the language you're testing against in the test matrix doesn't seem *that* ugly ;)

**Comment by hawkowl** [comment]
We also need a `-twtrunk` for Py3.5, then :shipit:

**Comment by glyph** [comment]
@hawkowl - `-twtrunk` is not necessary for a *release* (by definition it's not a release-supported configuration), and I wanted to avoid unnecessary builders. separate PR?

**Comment by hawkowl** [comment]
sure. :shipit:!

**Comment by glyph** [comment]
Release is on PyPI.

**Pull request merged**
