### PR TITLE
Added Klein extension support.

### PR DESCRIPTION
**Pull request by VRGhost**
Hello,

This pull request is to introduce support of the dynamic extension module loading into the `klein.ext` namespace.

I've also moved `_call` method from module static namespace to `Klein` object methods. This is because I'll have to inject to this exact spot in my future extension (I am planning to create an extension that introduces [`injector`](https://github.com/alecthomas/injector) support to Klein route handlers).

### CODE REVIEW

**Comment by brighid** [comment]
Is this PR still live?

**Comment by Alir3z4** [comment]
This is really good.
@hawkowl @VRGhost any update on this guys ?

**Comment by VRGhost** [comment]
Hello,

To be honest, I don't even remember this pull request now.
I'll take a look to see why the CI isn't happy.

**Comment by VRGhost** [comment]
Ha, it's been two years! No surprise I can't remember a thing.

**Comment by VRGhost** [comment]
The CI is now in the green. @hawkowl , your move.

**Comment by Alir3z4** [comment]
@VRGhost Thanks for the bold and heroic move.
Now, in @hawkowl we trust.

**Comment by hawkowl** [comment]
@VRGhost There seems to be a ``test-case-name`` which points somewhere that doesn't exist :) Maybe it wasn't committed to the index?

**Comment by tehasdf** [comment]
@VRGhost Is this really something that's desirable? 
Flask used to have something like this, but it turned out that keeping all extensions under a namespace package was just a pain for everyone involved, for no real benefit. It was quickly deprecated (first "soft"-deprecated by just telling people to not do that, and now properly). 

The import rewrite mechanism that rewrites `flask.ext.foo` to `flask_foo` was introduced BECAUSE of that, to make transition from .ext to `flask_foo` easier (backwards compat for apps using .ext).

Today, flask extensions are named `flask_foo` without any formalized checks, just by convention.

**Comment by glyph** [comment]
In order to be accepted, this would need some pretty major changes:

- It should probably use the Twisted plugin system, rather than its own ad-hoc import stuff, to grab the objects involved.
- I think @tehasdf has a good question - is it really desirable?  Maybe it's just a bad idea entirely.
- It will definitely need examples, documentation, and tests.

If you still think this should be done, please open an issue, so we can discuss the feature's desirability separately from any given implementation.  I am going to close this for now because I'm deeply doubtful about this particular implementation direction, but when the issue has been opened and some discussion proceeds, we might reopen it.

**Pull request closed without merging**
