### PR TITLE
Added documentation for using decorators and flexible route handling

### PR DESCRIPTION
**Pull request by larsx2**
The following Pull Request focuses on exploring different options while registering new routes on Klein. 
The example provided shows primarily two things:
- How to use decorators to avoid duplication of code i.e. request.setHeader('Content-Type', 'application/json') and an example of key authorization
- Show other ways to register routes dynamically wrapping the klein instance in a custom class as instance attribute

### CODE REVIEW

**Comment by glyph** [comment]
Hi @larsx2 !

Thank you for contributing to Klein.

Sorry for the extremely long wait.  We didn't (and still don't) have a great process in place to motivate folks to look at Klein pull requests; but at least I now have a recurring task to look at the list and try to provide review feedback.

This looks like a promising example, but I have a few questions about it:

- it seems like the example is doing a lot, but the blurb before it doesn't really do it justice
- this is a longish untested example.  could you possibly do it with a literalinclude rather than an in-line code block, so that we could add a test case to make sure it works as expected?
- could you perhaps shorten it a bit?
- run-once methods like `setupRoutes` don't really make sense as public methods; I think that should be in-line inside `__init__`, unless I'm misunderstanding something.

As it is I think it might be a little confusing, although I do think we should be documenting composability and good design patterns for klein apps, so I hope we can refine this a bit more.  If you have lost interest in the more-than-a-year since you submitted this I will of course understand, but I hope not :).

**Comment by glyph** [comment]
Ping - @larsx2 , still there?

**Comment by notoriousno** [comment]
@glyph This is a very good example and does need a bit more explanation.  I can definitely take a look at editing it to be more descriptive if @larsx2 has lost interest or doesn't answer.

**Comment by glyph** [comment]
@notoriousno - at this point, probably best to assume that will be the case.  If you'd like to open a new PR with these changes, we can close this one.

**Comment by larsx2** [comment]
Hey @glyph, im sorry for the delay, i just lost track of this. 

I can take a stab at this on the weekend, or if @notoriousno is on it already its all good.

**Comment by glyph** [comment]
@larsx2 - No worries. I just send the occasional ping to remind folks that their PRs live on…

Speaking of which…? :)

**Comment by notoriousno** [comment]
I just so happened to check my spam today and low and behold this notification was there :D I'll get started on this today.

**Comment by notoriousno** [comment]
@glyph, @larsx2 I've modified the original PR a bit. I'm not sure how you all feel about it so I'd like to air stuff out here before making a whole new PR. I felt some of the functions in the original example weren't really specific to klein or had a strange syntax that deviated too much from the simple syntax of klein (and subsequently flask and bottle). Also the example didn't show reusability. I kept the clever bits from the original example and displayed how it can be reusable without inheriting from ``Klein``:

``` python
from functools import wraps
import json
from klein import Klein

class JsonApi(object):
    """
    Reusable class for composing a JSON API easily with minimal
    repeated code.
    """

    def __init__(self, app=None, secret='twisted'):
        self.app = app if app else Klein()
        self.secret = secret

    def toJSON(self, data):
        """
        Serialize data to JSON
        """
        return json.dumps(data)

    def defaultMiddleware(self, f):
        """
        Middleware to set application/json as default header for
        all responses.
        """
        @wraps(f)
        def deco(*args, **kwargs):
            request = args[0]
            request.setHeader('Content-Type', 'application/json')
            return self.toJSON(f(*args, **kwargs))

        return deco

    def authenticate(self, f):
        """
        Middleware api-key authentication
        """
        @wraps(f)
        def deco(*args, **kwargs):
            request = args[0]
            apiKey = request.getHeader('Authorization')
            if not apiKey or apiKey != self.secret:
                request.setResponseCode(401)
                body = {
                    'scope': 'private',
                    'message': 'Sorry, valid credentials required to access content'}
                return body
            return f(*args, **kwargs)

        return deco

    def route(self, url, *args, **kwargs):
        """
        Extend the route functionality
        """
        def deco(f):
            restricted = kwargs.pop('restricted', False)
            if restricted:
                f = self.authenticate(f)
            f = self.defaultMiddleware(f)
            self.app.route(url, *args, **kwargs)(f)
        return deco


def main():
    main_app = Klein()
    json_api = JsonApi(app=main_app, secret='tw15t3d')

    @main_app.route('/')
    def home(request):
        return 'Hello World'

    @json_api.route('/jsonify', methods=['GET'])
    def jsonify(request):
        return {'foo': 'bar'}

    @json_api.route('/admin', restricted=True)
    def admin(request):
        return {'scope': 'private', 'message': 'Access restricted content'}

    @json_api.route('/admin/v2')
    @json_api.authenticate
    def admin_v2(request):
        return {'scope': 'private', 'message': 'Access restricted content'}

    main_app.run('localhost', 8080)

main()
```


Let me know if this is acceptable.

**Comment by larsx2** [comment]
I don't mind, the approach looks good to me. Feel free to modify as will @notoriousno. 👍

**Comment by notoriousno** [comment]
I've made a pull request #146 if anyone is interested in reviewing it. @glyph the critiques you've made have been implemented, let me know if it's to your liking.

**Comment by wsanchez** [comment]
Please update from trunk.

Apparently there's an "allow other contributors to push to this branch" button you can enable that would have allowed me to do that for you.

**Comment by glyph** [comment]
Hey @notoriousno - just checking in. Can you update from trunk as @wsanchez requested?

**Comment by notoriousno** [comment]
I've merged from the upstream master branch on my PR ( #146 ), this PR should most likely be closed.

**Comment by glyph** [comment]
Thanks for the update @notoriousno ! I'll review that branch instead.

**Comment by anekix** [comment]
@notoriousno 
> There are some stuff that don't work yet, like returning Deferreds, but I just wanted to give a quick update on what I'm thinking.

any updates on this?

**Pull request closed without merging**
