### PR TITLE
WIP: forms and sessions

### PR DESCRIPTION
**Pull request by glyph**
This PR has already gotten lots of design feedback and is (cough) in production in at least one place.

Its long and convoluted history needs cleaning up, it needs additional test coverage, it needs documentation and it might need to be split into multiple pieces, but it really should land (among other things it contains critically necessary CSRF protection for POST requests, and a session API that can actually provide that, unlike Twisted's very sad and disused excuse for sessions).

### CODE REVIEW

**Comment by glyph** [comment]
image
ITSHAPPENING.GIF

**Comment by wsanchez** [comment]
Definitely some good stuff here, but I do think that there's a lot of unrelated stuff happening all at once, so breaking this up into parts seems prudent.

**Comment by glyph** [comment]
> Definitely some good stuff here, but I do think that there's a lot of unrelated stuff happening all at once, so breaking this up into parts seems prudent.

Nothing in here is unrelated (everything apparently unrelated is a dependency of something else) but I'll turn this into a set of stacked PRs that make meaningful changes in each one so that it's possible to see those relationships.

**Comment by glyph** [comment]
I may end up landing this with the big red administrator button in the not too distant future.

I should begin by saying: this is a process failure and it is my fault.  I will blame this on my adorable child and me being a new first-time parent during the heaviest period of development on this branch.  Very rarely do I exercise administrative perogatives on Twisted projects to circumvent the usual process (I think "about once a decade" is probably an accurate estimate) so I feel compelled to leave some reasoning here:

1. This change adds several security-critical features to Klein, without which it's hard for me (knowing what I now know about web security) to recommend it to others.
2. The changes are intricately interrelated and extricating them from each other would require a substantial amount of additional effort.
3. While merging sans review is a violation of the *de jure* process as documented, the substantial amount of review feedback from multiple maintainers I've solicited and acted upon on multiple occasions I think follows the *spirit* of the process.  Or at least, I'd like to believe it does.
4. The changes are too big for anybody to reasonably review at once and it's not really fair to ask one person to shoulder the burden of crunching through it all in one sitting, even if someone did happen to have the time.
5. This branch has been in production at my employer for over a year now, so I think it probably works okay.  This is also one of the bigger deployments of Klein.  It also somewhat constrains the range of my responsiveness to certain kinds of review feedback: this branch inherently has a pretty robust compatibility contract, for me personally, at least.
6. On that same note, a couple of other folks - names withheld to protect the guilty - have privately commented to me that they're thinking of deploying this branch in production rather than the last release of Klein, for the reasons given in point 1. above.  The point of having a release process is to prevent things from reaching production until they're ready, and this horse may be well and truly out of the barn at this point.

All that said, I'm still adding test coverage to ensure it's got a proper set of regression tests, so if you have some inline comments you'd like to make, feel free to look at interesting sections of the diff and leave comments, I'm sure I'll still have some time to look at them.  Just don't feel like you need to absorb the whole thing if you have comments on a piece :).

**Comment by glyph** [comment]
I've removed the demo / sketch, and the untested SQL backend only used for same.  Despite codecov being persistently out to lunch now for some reason, I have locally validated that coverage is adequate.

As promised, administrative merge incoming.  I'll resurrect the SQL / Alchimia stuff in a separate PR, perhaps one that could actually be reviewed.

**Pull request merged**
