### PR TITLE
Add displayTracebacks argument to Klein.run.

### LINKED ISSUE #112: Disabling tracebacks in response should be much easier
By default Klein displays tracebacks in 500 response if unhandled error occurs. This is ok and useful for debugging but I think there should be some optional argument for run() disabling tracebacks and there should be information in documentation about this. 

Figuring out how to disable tracebacks in production is currently not obvious and requires you to go into Klein code find out it uses Site() object under the hood, find out this object has displayTraceback attribute and set this attribute to False on class level. 

So something like this:

``` python
from klein import Klein
from twisted.web.server import Site

app = Klein()
Site.displayTracebacks = False

@app.route('/')
def home(request):
    raise
    return 'Hello, world!'

app.run("localhost", 8080)
```

it would be better to simply have optional debug=True/False argument for `Klein().run()` that would set this for you.

### PR DESCRIPTION
**Pull request by evilham**
This enables per-Klein app control of traceback display.

Fixes #112

### CODE REVIEW

**Comment by wsanchez** [comment]
This might be a bit more than needed…  Seems like documenting this would be enough:

```python
from twisted.web.server import Site
Site.displayTracebacks = False
```

I'd be more inclined to set this to `False` in Klein… though I suppose that has the potential to effect other uses of `Site` in the same applications… though really that seems unlikely… but anyway it *could* be rude… but it seems really lame to have this on by default…

I think maybe should be a Twisted ticket, then… perhaps where an environment variable enables the behavior that sets the default to `True` but otherwise it defaults to `False`.

**Comment by evilham** [comment]
Hum, I actually agree with the overall rationale that `displayTracebacks` should be on by default. 

When you are just testing a new framework, the last thing you want is to be fiddling around tons of documentation and setting up the things that help you do stuff.

On the other hand, when you are deploying stuff, you should have a place that guides you do that.
When it comes to this particular thing, it means having an easy to change, well documented and *without side-effects* way to disable `displayTracebacks`.

In this regard, I'd think Django did a great job: the default config enables people to do what they want to do from moment zero, and they have a good "deployment" documentation.
This PR seems to me like a good step in that direction.

I think that the ticket you are suggesting is already linked to from the documentation I added:
https://twistedmatrix.com/trac/ticket/135

I don't see the point in setting `t.w.s.Site.displayTracebacks` to `False` from inside Klein.
By assuming that changing a global setting is OK, Klein is starting to assume that it's the only thing happening in that process and at hat it's OK to unnecessarily mess with Twisted internals.
I'd think that goes in a direction that defeats the flexibility of Twisted (and therefore Klein).

Notice that I did add documentation for `t.w.s.Site.displayTracebacks`, in case that is preferred by people. Most of the time though, the proposed `Klein.run(displayTracebacks=False)` would be enough, it's easy, documented, unobtrusive and without side-effects.

**Comment by glyph** [comment]
How about this, then:

Set a flag, `development=`

Make it force you to use 127.0.0.1, and also turn on displayTracebacks=True.

Give it a truthy default value, but deprecate this value; emit a warning if the user doesn't pass one explicitly.  Fix the docs to always pass it.

I think this will address both parties' concerns.

@evilham @wsanchez ?

**Comment by glyph** [comment]
> ```python
> from twisted.web.server import Site
> Site.displayTracebacks = False
> ```

(BTW, this is a super gross way to do that.  It's documented as an instance variable, and it's an accident that it works on the class.)

**Comment by evilham** [comment]
A `development` flag like that would be somewhat better indeed.

I just wouldn't necessarily go as far as forcing `localhost` binding (remember IPv6 is a thing :-D).
Development in a networked environment is not as weird as it sounds, nowadays there are tools like vagrant and so on, it really is not too weird.
Besides it gives a false sense of "people won't use it like that in production": if you use a reverse proxy, `localhost` binding may work anyway and still expose the service to the internetz, so it feels like wasted energy and loss of flexibility in vain.

Probably with the proper documentation changes + warning when not set, it'd be enough.

**Comment by wsanchez** [comment]
I like the `development` idea because it's what I'd want, but I think I agree with @evilham in that it's better to be explicit about each knob.

I don't see @glyph's argument about why displayTracebacks should be on by default anywhere here or in #112, but I'm pretty skeptical.  Turning on debugging crap in development is not an abnormal thing, and turning on security holes by default seems profoundly misguided to me.  But being able to turn it off easily is good enough, I guess.

**Comment by wsanchez** [comment]
@evilham This PR look good to me, but you'll need to fix a trivial conflict for a review.

**Pull request merged**
